### ISSUE TITLE
System clipboard not working

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes#13]
The system clipboard does not work from/to Shoes on Windows. It does work properly on MacOS X 10.9+ and 10.6 (custom build).

**_TEST SCENARIOS_**
**TEST (1):**
* Run the Shoes script below using Shoes
* Open Notepad, write some text, select it and copy it to the system clipboard
* Click on paste button in the Shoes script

_EXPECTED RESULT_ **Should paste the previously selected text into the Shoes script**

**TEST (2):**
* Click on copy button in the Shoes script
* Return to the Notepad application and paste from the system clipboard

_EXPECTED RESULT_ **Should paste _this is a Shoes string._ into Notepad.**

**TEST (3)**
* Go back to the Shoes script and click on paste

_EXPECTED RESULT_ **Should paste _this is a Shoes string._ into the Shoes script.**

```ruby
Shoes.app(:title => "Copy and Paste", :width => 450, :height => 250) {
   button "copy" do
      self.clipboard = "this is a Shoes string."
   end
   button "paste" do
      para clipboard()
   end
}
```

**Comment by ccoupe** [comment]
In Linux, the paste button works but copy button doesn't.

**Comment by ccoupe** [comment]
Around line 1462 in gtk2.c, two funtions: use GDK_SELECTION_CLIPBOARD in place of GDK_SELECTION_PRIMARY.

It's working on Win 7 and Linux.  Try http://walkabout.mvmanila.com/public/shoes/shoes-3.2.20-gtk2-32.exe

**Comment by BackOrder** [comment]
Confirmed working on Windows 8.

**Comment by ccoupe** [comment]
It's about time we got an easy one to fix.
